services:
  postgres:
    image: postgres:latest
    container_name: RecipeIt
    environment:
      POSTGRES_DB: RecipeIt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always

  recipe-app:
    image: image-recipe:0.0.1-SNAPSHOT
    container_name: RecipeIt-App
    ports:
        - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RecipeIt
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      - postgres
    restart: on-failure

